name: Build Docker Image with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Generate settings.xml in project root
        run: |
          cat <<EOF > ./settings.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_USER}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t solo-leveling-notification .

      - name: Clean up settings.xml (for security)
        run: rm -f ./settings.xml